Expose bootstrap out of the systemd

diff --git a/target/init b/target/init
--- a/target/init
+++ b/target/init
@@ -12,6 +12,19 @@ echo
 echo "${HOME_URL}"
 echo
 
+if ! mount -t efivarfs efivars /bootstrap/efivars; then
+  echo "Mount efivarfs for bootstrap failed!"
+  exit 1
+fi
+
+if ! bootstrap \
+  --efivars /bootstrap/efivars \
+  --generator /bootstrap/generator.tmpl
+then
+  echo "Bootstrap failed!"
+  exit 1
+fi
+
 exec \
   /usr/lib/systemd/systemd \
     --log-level=err \
